# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='id_15',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('keywords', models.CharField(max_length=30, verbose_name='文章关键词')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('img', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
        ),
    ]
