# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunbo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('img', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AlterModelOptions(
            name='id_15',
            options={'verbose_name': '博文详情', 'verbose_name_plural': '博文详情'},
        ),
        migrations.AlterField(
            model_name='id_15',
            name='title',
            field=models.CharField(max_length=40, verbose_name='文章标题'),
        ),
    ]
