# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190831_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='img',
            field=models.TextField(verbose_name='封面URL'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='url',
            field=models.TextField(verbose_name='详情链接'),
        ),
    ]
