# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190831_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='热文ID')),
                ('title', models.CharField(max_length=40, verbose_name='热文标题')),
                ('source', models.CharField(max_length=20, verbose_name='热文来源')),
                ('comment', models.IntegerField(verbose_name='评论数量')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '头条热文',
                'verbose_name_plural': '头条热文',
            },
        ),
    ]
