# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190901_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewen',
            name='comment',
            field=models.IntegerField(verbose_name='评论数量'),
        ),
    ]
