# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190901_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_15',
            name='title',
            field=models.CharField(max_length=60, verbose_name='文章标题'),
        ),
    ]
