# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190901_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id_15',
            old_name='img',
            new_name='img_url',
        ),
    ]
