# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190903_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_1708',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('keywords', models.CharField(max_length=30, verbose_name='文章关键词')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('img_url', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '博文详情',
                'verbose_name_plural': '博文详情',
            },
        ),
        migrations.CreateModel(
            name='id_481',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('keywords', models.CharField(max_length=30, verbose_name='文章关键词')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('img_url', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '博文详情',
                'verbose_name_plural': '博文详情',
            },
        ),
        migrations.CreateModel(
            name='id_519',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('keywords', models.CharField(max_length=30, verbose_name='文章关键词')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('img_url', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '博文详情',
                'verbose_name_plural': '博文详情',
            },
        ),
        migrations.CreateModel(
            name='id_583',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('keywords', models.CharField(max_length=30, verbose_name='文章关键词')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('img_url', models.URLField(verbose_name='封面URL')),
                ('url', models.URLField(verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '博文详情',
                'verbose_name_plural': '博文详情',
            },
        ),
    ]
