# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190713_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='news',
            name='attachment',
            field=models.ImageField(upload_to='', verbose_name='封面图片'),
        ),
    ]
